# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Wilde On!
tagline:          'This time it might stay the same!'
description:      'A blog mainly about technology, bushwalking and music.  All views are my own'
url:              http://wilde.id.au

author:
  name:           'Stewart Wilde'
  url:            https://twitter.com/stewartwilde

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/stewba/hyde
